//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAlumnos_172.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_ALUMNOS_172
    {
        public int ID { get; set; }
        public string APELLIDO { get; set; }
        public string NOMBRE { get; set; }
        public string SEXO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
